[project]
authors = ["Pranesh A S"]
entry = "main.sw"
license = "Apache-2.0"
name = "microstable-sway"

[dependencies]
pyth_interface = { git = "https://github.com/pyth-network/pyth-crosschain", tag = "pyth-fuel-contract-v0.5.0" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.1" }
